### PR TITLE
mongo/migrate: minimal mongo migrations infrastructure

### PR DESCRIPTION
**Pull request by mchalski**
a Migrator applies Migrations provided by the app at startup.
to initialize mongo versioning, define a DummyMigrator which will simply
bump the db version to the target one.

will add tests after a quick review.

Issues: MEN-889

Signed-off-by: mchalczynski <marcin.chalczynski@rndity.com>

@maciejmrowiec @bboozzoo

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
in general looks good, one thing doe we will need for sure is SemVer parser so we can compare older/newer (if stored ver < my version) -> Up

**Comment by mchalski** [comment]
@maciejmrowiec so like a Version struct (to string, from string), with maj, min, patch integers and comparison?

 I should have it in reflog somewhere, that's what I did at the start, but then simplified to lexical comparisons (e.g. "1.1.1" > "1.0.0", etc.)

**Comment by maciejmrowiec** [comment]
yea something like this

**Comment by mchalski** [comment]
@maciejmrowiec  ok, added the struct. Can I merge this after I write some tests? I'd start introducing it to the services then.

**Pull request merged**
