### PR TITLE
MEN-2027 - get rid of useless log line about unknown auth method Basic. 

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
@merlin-northern I like it. Are you gonna follow up on this one?

**Comment by merlin-northern** [comment]
> @merlin-northern I like it. Are you gonna follow up on this one?

just click approve and I will merge. I guess someone needs to review it.

**Comment by oleorhagen** [comment]
Rebase it first, so that we have the CI give it green

**Comment by oleorhagen** [comment]
@merlin-northern why did u merge master, instead of rebasing?

**Comment by merlin-northern** [comment]
> @merlin-northern why did u merge master, instead of rebasing?

I clicked "Update branch" below, usually it worked.

**Comment by merlin-northern** [comment]
> @merlin-northern I like it. Are you gonna follow up on this one?

take a look Ole. almost a year passed! @oleorhagen

**Comment by alfrunes** [comment]
Solved recently in #86

**Pull request closed without merging**
